/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import controller.RegisterDoctorController;
import controller.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class AdminView extends javax.swing.JFrame {

    private int x, y;
    private model.User user;
    private final model.DataStore store = model.DataStore.getInstance();

    public AdminView(model.User loggedUser) {
        initComponents();
        this.user = loggedUser;
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        loadDoctorComboBox();
        loadPatientComboBox();
    }

    private void loadDoctorComboBox() {
        cmbSelectDoctor.removeAllItems();
        cmbSelectDoctor.addItem("Select one");
        for (model.Doctor d : store.getDoctors()) {
            cmbSelectDoctor.addItem(String.valueOf(d.getId()));
        }
    }

    private void loadPatientComboBox() {
        cmbSelectPatient.removeAllItems();
        cmbSelectPatient.addItem("Select one");
        for (model.Patient p : store.getPatients()) {
            cmbSelectPatient.addItem(String.valueOf(p.getId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new packagee.PanelRound();
        panelRound2 = new packagee.PanelRound();
        btnClose = new javax.swing.JButton();
        lblAdminView = new javax.swing.JLabel();
        panelRound3 = new packagee.PanelRound();
        btnGoToDoctor = new javax.swing.JButton();
        btnGoToPatient = new javax.swing.JButton();
        lblDocFirstname = new javax.swing.JLabel();
        txtDocFirstname = new javax.swing.JTextField();
        lblDocLastname = new javax.swing.JLabel();
        txtDocLastname = new javax.swing.JTextField();
        lblDocId = new javax.swing.JLabel();
        txtDocId = new javax.swing.JTextField();
        lblDocSpecialty = new javax.swing.JLabel();
        lblDocLicence = new javax.swing.JLabel();
        txtDocLicence = new javax.swing.JTextField();
        lblDocOffice = new javax.swing.JLabel();
        txtDocOffice = new javax.swing.JTextField();
        lblDocUsername = new javax.swing.JLabel();
        txtDocUsername = new javax.swing.JTextField();
        lblDocPassword = new javax.swing.JLabel();
        txtDocPassword = new javax.swing.JTextField();
        lblDocConfirmPwd = new javax.swing.JLabel();
        txtDocConfirmPwd = new javax.swing.JTextField();
        cmbDocSpecialty = new javax.swing.JComboBox<>();
        btnSaveDoctor = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmbSelectDoctor = new javax.swing.JComboBox<>();
        lblSelectPatient = new javax.swing.JLabel();
        lblSelectDoctor = new javax.swing.JLabel();
        cmbSelectPatient = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setRadius(50);

        panelRound2.setRadius(50);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblAdminView.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAdminView.setText("ADMIN VIEW");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAdminView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdminView))
        );

        btnGoToDoctor.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnGoToDoctor.setText("DOCTOR VIEW");
        btnGoToDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToDoctorActionPerformed(evt);
            }
        });

        btnGoToPatient.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnGoToPatient.setText("PATIENT VIEW");
        btnGoToPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToPatientActionPerformed(evt);
            }
        });

        lblDocFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocFirstname.setText("Firstname");

        txtDocFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocLastname.setText("Lastname");

        txtDocLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocId.setText("ID");

        txtDocId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocSpecialty.setText("Specialty");

        lblDocLicence.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocLicence.setText("License Number");

        txtDocLicence.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocOffice.setText("Assigned office");

        txtDocOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocUsername.setText("User");

        txtDocUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocPassword.setText("Password");

        txtDocPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocConfirmPwd.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocConfirmPwd.setText("Password confirmation");

        txtDocConfirmPwd.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbDocSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbDocSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnSaveDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSaveDoctor.setText("Save");
        btnSaveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDoctorActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cmbSelectDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbSelectDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblSelectPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblSelectPatient.setText("Doctor");

        lblSelectDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblSelectDoctor.setText("Patient");

        cmbSelectPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbSelectPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnSaveDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDocFirstname)
                                    .addComponent(lblDocSpecialty))
                                .addGap(18, 18, 18)
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(cmbDocSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDocLicence)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(txtDocFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lblDocLastname)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDocId)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(lblDocOffice)
                                .addGap(18, 18, 18)
                                .addComponent(txtDocOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelRound3Layout.createSequentialGroup()
                                    .addComponent(lblDocUsername)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDocUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelRound3Layout.createSequentialGroup()
                                    .addComponent(lblDocPassword)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDocPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelRound3Layout.createSequentialGroup()
                                    .addComponent(lblDocConfirmPwd)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDocConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGoToDoctor)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cmbSelectDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblSelectPatient)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(318, 318, 318)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGoToPatient)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(cmbSelectPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblSelectDoctor)))
                .addGap(88, 88, 88))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocFirstname)
                    .addComponent(txtDocFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocLastname)
                    .addComponent(txtDocLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocId)
                    .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocSpecialty)
                    .addComponent(cmbDocSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocLicence)
                    .addComponent(txtDocLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDocOffice)
                    .addComponent(txtDocOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocUsername)
                            .addComponent(txtDocUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocPassword)
                            .addComponent(txtDocPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocConfirmPwd)
                            .addComponent(txtDocConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblSelectPatient)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSelectDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnGoToDoctor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnSaveDoctor)
                .addGap(123, 123, 123)
                .addComponent(btnLogout)
                .addGap(38, 38, 38))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblSelectDoctor)
                .addGap(18, 18, 18)
                .addComponent(cmbSelectPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnGoToPatient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDoctorActionPerformed
        RegisterDoctorController ctrl = new RegisterDoctorController();
        Response response = ctrl.register(
            user,
            txtDocId.getText(),
            txtDocUsername.getText(),
            txtDocFirstname.getText(),
            txtDocLastname.getText(),
            txtDocPassword.getText(),
            txtDocConfirmPwd.getText(),
            (String) cmbDocSpecialty.getSelectedItem(),
            txtDocLicence.getText(),
            txtDocOffice.getText()
        );
        if (response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Success", JOptionPane.INFORMATION_MESSAGE);
            txtDocFirstname.setText(""); txtDocLastname.setText(""); txtDocId.setText("");
            txtDocLicence.setText(""); txtDocOffice.setText(""); txtDocUsername.setText("");
            txtDocPassword.setText(""); txtDocConfirmPwd.setText("");
            cmbDocSpecialty.setSelectedIndex(0);
            loadDoctorComboBox();
        } else {
            JOptionPane.showMessageDialog(this, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveDoctorActionPerformed

    private void btnGoToDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToDoctorActionPerformed
        String selected = (String) cmbSelectDoctor.getSelectedItem();
        if (selected == null || selected.equals("Select one")) {
            JOptionPane.showMessageDialog(this, "Please select a doctor", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long doctorId = Long.parseLong(selected);
        model.Doctor doctor = (model.Doctor) store.findUserById(doctorId);
        if (doctor == null) {
            JOptionPane.showMessageDialog(this, "Doctor not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.setVisible(false);
        new DoctorView(user, doctor).setVisible(true);
    }//GEN-LAST:event_btnGoToDoctorActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
        new LoginRegisterView().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnGoToPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToPatientActionPerformed
        String selected = (String) cmbSelectPatient.getSelectedItem();
        if (selected == null || selected.equals("Select one")) {
            JOptionPane.showMessageDialog(this, "Please select a patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long patientId = Long.parseLong(selected);
        model.Patient patient = (model.Patient) store.findUserById(patientId);
        if (patient == null) {
            JOptionPane.showMessageDialog(this, "Patient not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.setVisible(false);
        new PatientView(user, patient).setVisible(true);
    }//GEN-LAST:event_btnGoToPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGoToDoctor;
    private javax.swing.JButton btnGoToPatient;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSaveDoctor;
    private javax.swing.JComboBox<String> cmbDocSpecialty;
    private javax.swing.JComboBox<String> cmbSelectDoctor;
    private javax.swing.JComboBox<String> cmbSelectPatient;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdminView;
    private javax.swing.JLabel lblDocConfirmPwd;
    private javax.swing.JLabel lblDocFirstname;
    private javax.swing.JLabel lblDocId;
    private javax.swing.JLabel lblDocLastname;
    private javax.swing.JLabel lblDocLicence;
    private javax.swing.JLabel lblDocOffice;
    private javax.swing.JLabel lblDocPassword;
    private javax.swing.JLabel lblDocSpecialty;
    private javax.swing.JLabel lblDocUsername;
    private javax.swing.JLabel lblSelectDoctor;
    private javax.swing.JLabel lblSelectPatient;
    private packagee.PanelRound panelRound1;
    private packagee.PanelRound panelRound2;
    private packagee.PanelRound panelRound3;
    private javax.swing.JTextField txtDocConfirmPwd;
    private javax.swing.JTextField txtDocFirstname;
    private javax.swing.JTextField txtDocId;
    private javax.swing.JTextField txtDocLastname;
    private javax.swing.JTextField txtDocLicence;
    private javax.swing.JTextField txtDocOffice;
    private javax.swing.JTextField txtDocPassword;
    private javax.swing.JTextField txtDocUsername;
    // End of variables declaration//GEN-END:variables
}
